repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args:
          [--exclude, features, --ignore, "E501", --fix, --exit-non-zero-on-fix, --select, "E,F,I"]
      - id: ruff-format