name: Integration Tests

on:
  pull_request:
    branches: ["master"]

env:
  POETRY_VIRTUALENVS_CREATE: "false"
  POETRY_VERSION: "1.8.5"

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        env:
          PIPX_DEFAULT_PYTHON: python${{ matrix.python-version }}
        run: pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: poetry install

      - name: Run integration tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: poetry run pytest
